"""Write generated documentation files to the output directory."""

from __future__ import annotations

from pathlib import Path


class DocWriter:
    def __init__(self, output_dir: str, repo_path: str = ".") -> None:
        self.output_dir = Path(repo_path) / output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def write(self, filename: str, content: str) -> Path:
        """Write content to a file in the output directory."""
        path = self.output_dir / filename
        path.write_text(content, encoding="utf-8")
        return path

    def write_developer(self, content: str) -> Path:
        return self.write("DEVELOPER.md", content)

    def write_user_guide(self, content: str) -> Path:
        return self.write("USER_GUIDE.md", content)

    def write_notebooklm(self, developer: str, user_guide: str, source: str) -> Path:
        combined = "\n\n---\n\n".join(filter(None, [developer, user_guide]))
        footer = (
            "\n\n---\n\n"
            f"*Generated by [docforge](https://github.com/nikolareljin/docforge) "
            f"from `{source}`. "
            "Optimized for import into [Google NotebookLM](https://notebooklm.google.com/).*"
        )
        return self.write("NOTEBOOKLM.md", combined + footer)
